### ISSUE TITLE
EAS Build Failed

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [bndkt/react-native-app-clip#4]
The EAS Build is failing with the following error: Could not find target '....Clip' in project.pbxproj
Do I need to eject the project in order to make the App Clip work?

I actually followed your instructions in the README, except for the prebuild step, because I haven't ejected the app.

**Comment by bndkt** [comment]
Hi, sorry for the delay I was traveling for a while. I just published a new version of the package (0.0.16). Please update to a new version and make sure that the app.json includes a "bundleIdentifier" value for iOS.

**Comment by mariomurrent-softwaresolutions** [comment]
Thx, the bundle identifier of the app is in the app.json but the build still fails.

Any ideas what I'm missing?

**Comment by bndkt** [comment]
Have you created the app identifier for the Clip in the Apple Developer portal according to the readme? If that's not it, could you post the logs from EAS so that I can investigate?

**Comment by mariomurrent-softwaresolutions** [comment]
Yes and the build is also trying to assign the correct profile

```
Configuring Xcode project
2
Assigning provisioning profile '*[expo] com.**** AdHoc 1642490403464' (Apple Team ID: *******) to target 'DEC11220'
3
Assigning provisioning profile '*[expo] com.*****.Clip AdHoc 1659080180484' (Apple Team ID: *******) to target '*****Clip'
4
Could not find target '*****Clip' in project.pbxproj
```

This is the error I'm seeing in the EAS build. I can try to build it locally. Maybe I'm getting more information there.

**Comment by mariomurrent-softwaresolutions** [comment]
I will need more time to make the build run locally. I'm getting different errors not related to the AppClip.

**Comment by mariomurrent-softwaresolutions** [comment]
Actually no idea why it is failing :(

**Comment by bndkt** [comment]
Ok curious. Does it build when you remove react-native-app-clip from app.json?

**Comment by mariomurrent-softwaresolutions** [comment]
Yes, without it EAS build is working fine - maybe I need to do a clean setup? And try out a clean setup?

**Comment by mariomurrent-softwaresolutions** [comment]
@bndkt It is building locally. Should the iOS Folder contain a separate folder for the app clip?

**Comment by bndkt** [comment]
I have published a major update to this package. I'm going to close this issue for now, please open a new one if the problem appears again.
